// Package wtc GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package wtc

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "miskadl09@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/data": {
            "get": {
                "description": "get information from Bearer JWT Access Token(oAuth)",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "get profile information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "H.Authorization: Bearer ` + "`" + `token` + "`" + `",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.GetProfileInfoResponseOK"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.GetProfileInfoResponseBR"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "login into an account",
                "parameters": [
                    {
                        "description": "user log model",
                        "name": "LogProfileModel",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.LogProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.LogProfileResponseOK"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.LogProfileResponseBR"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "register new profile to be able to use WTC.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "register new profile in WTC system",
                "parameters": [
                    {
                        "description": "user reg model",
                        "name": "CreateProfileModel",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.RegProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.RegProfileResponseOK"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.RegProfileResponseBR"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/model.RegProfileResponseFN"
                        }
                    }
                }
            }
        },
        "/update": {
            "get": {
                "description": "update profile by passing access token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "update profile",
                "parameters": [
                    {
                        "description": "update profile model",
                        "name": "UpdProfileModel",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.UpdateProfileResponseOK"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.UpdateProfileResponseBR"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.GetProfileInfoResponseBR": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "A response returned from the server.",
                    "type": "string"
                }
            }
        },
        "model.GetProfileInfoResponseOK": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "sex": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "model.LogProfileRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "user's email",
                    "type": "string"
                },
                "password": {
                    "description": "user's password",
                    "type": "string"
                }
            }
        },
        "model.LogProfileResponseBR": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "A response returned from the server.\ne.g. \"No records were found\".",
                    "type": "string"
                }
            }
        },
        "model.LogProfileResponseOK": {
            "type": "object",
            "properties": {
                "access_token": {
                    "description": "Access token to auth API requests.",
                    "type": "string"
                },
                "refresh_token": {
                    "description": "Refresh token to recreate access token.",
                    "type": "string"
                }
            }
        },
        "model.RegProfileRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "user's email",
                    "type": "string"
                },
                "password": {
                    "description": "user's password",
                    "type": "string"
                },
                "username": {
                    "description": "user's username",
                    "type": "string"
                }
            }
        },
        "model.RegProfileResponseBR": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "A response returned from the server.",
                    "type": "string"
                }
            }
        },
        "model.RegProfileResponseFN": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "A response returned from the server.\ne.g. \"ERROR: duplicate key value violates unique constraint\".",
                    "type": "string"
                }
            }
        },
        "model.RegProfileResponseOK": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "A response returned from the server.\ne.g. \"Successfully registered\".",
                    "type": "string"
                }
            }
        },
        "model.UpdateProfileRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "sex": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "model.UpdateProfileResponseBR": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "A response returned from the server.",
                    "type": "string"
                }
            }
        },
        "model.UpdateProfileResponseOK": {
            "type": "object",
            "properties": {
                "affected_rows": {
                    "description": "How many rows changed",
                    "type": "integer"
                },
                "message": {
                    "description": "A response returned from the server.",
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "0.4+05-01-2022-22:22",
	Host:        "localhost:9000",
	BasePath:    "/api/v1",
	Schemes:     []string{"http"},
	Title:       "WTC ACCOUNT SERVICE",
	Description: "Account service for WTC.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register("swagger", &s{})
}
